apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ade4zjcii-dotnet-basic
  janus-idp.io/tekton: ade4zjcii-dotnet-basic
  backstage.io/kubernetes-id: ade4zjcii-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ade4zjcii-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
